### ISSUE TITLE
Question: This plugin or https://github.com/ocaml/merlin

### ISSUE THREAD

**Issue by Uzaaft** [tjdevries/ocaml.nvim#4]
Just wondering,
How does this plugin stand in relation with https://github.com/ocaml/merlin
Any reason to choose this plugin over merlin, or should they be used together?

**Comment by tjdevries** [comment]
I don't think you would need merlin anymore - if there are some features not covered by LSP and this plugin, I'd love to hear about them :)

**Comment by Uzaaft** [comment]
Appreciate it! I'll add it to [Astronvim/astrocommunity](https://github.com/AstroNvim/astrocommunity) as the default in our ocaml pack then :)

**Comment by Uzaaft** [comment]
\

> Appreciate it! I'll add it to https://github.com/AstroNvim/astrocommunity as the default in our ocaml pack then :)
